SELECT
    RECORD_CONTENT:chamberId::INT AS chamber_id,
    RECORD_CONTENT:traceParams:T_L_Tmp::FLOAT AS actual_temp,
    SNOWFLAKE.ML.PREDICT('TEMP_PREDICTION_MODEL_V1',
        OBJECT_CONSTRUCT(
            'CHAMBER_ID', RECORD_CONTENT:chamberId::INT,
            'DQ_A', TRY_TO_NUMBER(RECORD_CONTENT:traceParams:DQ_a),
            'H_L_LD', TRY_TO_NUMBER(RECORD_CONTENT:traceParams:H_L_Ld),
            'H_L_GD_RL_PRS', TRY_TO_NUMBER(RECORD_CONTENT:traceParams:H_L_Gd_Rl_Prs)
        )
    ) AS predicted_temp
FROM KAFKA_DB.PUBLIC.TRACE_DATA
WHERE
    RECORD_CONTENT:traceParams:T_L_Tmp IS NOT NULL
LIMIT 10;

SHOW MODELS IN DATABASE KAFKA_DB;


CREATE OR REPLACE FUNCTION KAFKA_DB.PUBLIC.test_python_312()
RETURNS STRING
LANGUAGE PYTHON
RUNTIME_VERSION = '3.12'
PACKAGES = ('snowflake-snowpark-python')
HANDLER = 'handler'
AS $$
def handler():
    import sys
    return f"Python {sys.version}"
$$;

SELECT KAFKA_DB.PUBLIC.test_python_312();

use DATABASE KAFKA_DB;



USE ROLE ACCOUNTADMIN;
SELECT
FUNCTION_CATALOG,  -- same as database
FUNCTION_SCHEMA,
FUNCTION_NAME,
FUNCTION_OWNER,
FUNCTION_LANGUAGE,
DATE(CREATED) AS DATE_CREATED,
DATE(LAST_ALTERED) AS DATE_MODIFIED,
RUNTIME_VERSION,
-- FROM INFORMATION_SCHEMA.FUNCTIONS   -- single database
FROM SNOWFLAKE.ACCOUNT_USAGE.FUNCTIONS   -- entire account
WHERE FUNCTION_LANGUAGE = 'PYTHON'
AND RUNTIME_VERSION = '3.12'
ORDER BY 1, 2, 3;
