

CREATE SCHEMA KAFKA_DB.analyst_views;
GRANT ALL PRIVILEGES ON SCHEMA KAFKA_DB.analyst_views TO ROLE KAFKA_ROLE;

USE ROLE KAFKA_ROLE;
USE DATABASE KAFKA_DB;
USE SCHEMA ANALYST_VIEWS;

CREATE OR REPLACE VIEW KAFKA_DB.ANALYST_VIEWS.sales_data_v AS
SELECT date, sales
FROM KAFKA_DB.PUBLIC.historical_sales_data
WHERE store_id = 1 AND item = 'jacket';

SELECT * FROM sales_data_v;
SELECT * FROM sales_data_v LIMIT 1;

GRANT SELECT ON TABLE KAFKA_DB.PUBLIC.HISTORICAL_SALES_DATA TO ROLE KAFKA_ROLE;


CREATE OR REPLACE SNOWFLAKE.ML.FORECAST data_model1(
  INPUT_DATA => TABLE(sales_data_v),
  TIMESTAMP_COLNAME => 'date',
  TARGET_COLNAME => 'sales'
);

call data_model1!FORECAST(FORECASTING_PERIODS => 3);


CALL data_model1!FORECAST(FORECASTING_PERIODS => 3, CONFIG_OBJECT => {'prediction_interval': 0.8});

-- reset
SHOW SNOWFLAKE.ML.FORECAST;

DROP SNOWFLAKE.ML.FORECAST data_model1;
